blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Support and questions
    url: https://github.com/nak-ventures/serversentry/discussions
    about: Ask and answer questions here.
  - name: â„¹ï¸ View the Common Issues page
    url: https://serversentry.dev/guide/common-issues
    about: Find information about commonly encountered problems.
